Deep Learning project - Customer churn prediction-

    Read the dataset
    Drop the columns which are unique for all users like IDs (2.5 points)
    Distinguish the feature and target set (2.5 points)
     Divide the data set into Train and test sets
    Normalize the train and test data (2.5 points)
     Initialize & build the model (10 points)
    Optimize the model (5 points)
    Predict the results using 0.5 as a threshold (5 points)
     Print the Accuracy score and confusion matrix (2.5 points)


In [5]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [6]:
import tensorflow as tf

In [94]:
df=pd.read_csv('C://Users//Sandhyash//Downloads//Churn_Modelling.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [95]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [96]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Geography']=le.fit_transform(df['Geography'])
#pd.get_dummies(df,prefix=None, prefix_sep='',columns=['Gender', 'Geography'], drop_first=True)
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [97]:
df=df.drop(columns=['CustomerId', 'Surname', 'RowNumber'], axis=1)
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [98]:
#df=df.drop(columns=['CustomerId'], axis=1) already done in above step

X=df.drop(columns=['Exited']) # independent features
y=df['Exited'] #dependent or target feature

Normalize the train and test data (2.5 points)
 Initialize & build the model (10 points)
Optimize the model (5 points)
Predict the results using 0.5 as a threshold (5 points)
 Print the Accuracy score and confusion matrix (2.5 points)

In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.02, random_state=42)

In [100]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9800, 10), (200, 10), (9800,), (200,))

In [101]:
X_train.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
5198          604          0       1   40       1   84315.02              1   
8846          571          0       0   53       2       0.00              2   
259           850          1       1   38       3   54901.01              1   
3790          596          2       0   54       0   78126.28              1   
9202          528          0       1   31       9  120962.59              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
5198          0               0         36209.10  
8846          1               0         28045.77  
259           1               1        140075.55  
3790          1               1        153482.91  
9202          1               0          5419.31

In [102]:
df.dtypes

CreditScore          int64
Geography            int32
Gender               int32
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [103]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.fit_transform(X_test)

In [104]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization
from sklearn.metrics import confusion_matrix

In [105]:
model= Sequential()
b_norm= BatchNormalization()

In [106]:
model.add(Dense(32, activation='relu',input_shape=(X_train.shape[1],)))
#model.add(Dense(activation='relu', input_dim=11, units=))
#model.add(Dense(5, activation='relu'))

In [107]:
model.add(Dense(1, activation='sigmoid'))

In [108]:
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='SGD', metrics=['accuracy'],loss='binary_crossentropy')

In [109]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 32)                352       
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 33        
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 2         
Total params: 387
Trainable params: 387
Non-trainable params: 0
_________________________________________________________________


In [70]:
model.fit(X_train, y_train,
         epochs=50,
         validation_data=(X_test, y_test),
         batch_size=32)

Train on 9800 samples, validate on 200 samples
Epoch 1/50
9800/9800 [==============================] - 0s 25us/sample - loss: 0.3896 - acc: 0.8406 - val_loss: 0.4115 - val_acc: 0.8300
Epoch 2/50
9800/9800 [==============================] - 0s 24us/sample - loss: 0.3869 - acc: 0.8416 - val_loss: 0.4087 - val_acc: 0.8300
Epoch 3/50
9800/9800 [==============================] - 0s 24us/sample - loss: 0.3842 - acc: 0.8430 - val_loss: 0.4066 - val_acc: 0.8300
Epoch 4/50
9800/9800 [==============================] - 0s 23us/sample - loss: 0.3815 - acc: 0.8443 - val_loss: 0.4034 - val_acc: 0.8250
Epoch 5/50
9800/9800 [==============================] - 0s 26us/sample - loss: 0.3790 - acc: 0.8449 - val_loss: 0.4002 - val_acc: 0.8300
Epoch 6/50
9800/9800 [==============================] - 0s 23us/sample - loss: 0.3766 - acc: 0.8458 - val_loss: 0.3971 - val_acc: 0.8300
Epoch 7/50
9800/9800 [==============================] - 0s 23us/sample - loss: 0.3742 - acc: 0.8471 - val_loss: 0.3942 - val_acc: 0

In [76]:
y_pred=model.predict(X_test)
y_pred

array([[0.0368945 ],
       [0.02596569],
       [0.14777777],
       [0.17767322],
       [0.05289298],
       [0.00745142],
       [0.17505345],
       [0.05688423],
       [0.3935157 ],
       [0.47572014],
       [0.8234509 ],
       [0.87744427],
       [0.4867664 ],
       [0.5173214 ],
       [0.00920069],
       [0.10267287],
       [0.06933871],
       [0.22800013],
       [0.01923463],
       [0.04076836],
       [0.1463778 ],
       [0.00988334],
       [0.13354847],
       [0.2337097 ],
       [0.06488526],
       [0.22838467],
       [0.07964566],
       [0.01812103],
       [0.04415956],
       [0.10575941],
       [0.09080595],
       [0.05263406],
       [0.16114512],
       [0.01999635],
       [0.1220158 ],
       [0.6965036 ],
       [0.46274346],
       [0.03788579],
       [0.21054432],
       [0.04004654],
       [0.14129525],
       [0.45071402],
       [0.01366702],
       [0.0870392 ],
       [0.2742323 ],
       [0.10484767],
       [0.03113264],
       [0.283

In [79]:
y_pred=y_pred>.5
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [80]:
cm= confusion_matrix(y_test, y_pred)
cm

array([[156,   4],
       [ 25,  15]], dtype=int64)

Model clasification accuracy on validation data is 86.50%

Optimizing the model

In [112]:
#model.add(b_norm)
model.add(Dense(32, activation='relu',input_shape=(X_train.shape[1],)))
#model.add(b_norm)
model.add(Dense(16, activation='relu'))
#model.add(b_norm)
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', metrics=['accuracy'],loss='binary_crossentropy')

In [113]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 32)                352       
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 33        
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 2         
_________________________________________________________________
batch_normalization_2 (Batch (None, 1)                 4         
_________________________________________________________________
dense_18 (Dense)             (None, 32)                64        
_________________________________________________________________
dense_19 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_20 (Dense)             (None, 16)               

In [86]:
model.fit(X_train, y_train,
         epochs=50,
         validation_data=(X_test, y_test),
         batch_size=32)

Train on 9800 samples, validate on 200 samples
Epoch 1/50
9800/9800 [==============================] - 1s 59us/sample - loss: 0.4985 - acc: 0.8330 - val_loss: 0.3695 - val_acc: 0.8650
Epoch 2/50
9800/9800 [==============================] - 0s 43us/sample - loss: 0.3525 - acc: 0.8588 - val_loss: 0.3565 - val_acc: 0.8500
Epoch 3/50
9800/9800 [==============================] - 0s 40us/sample - loss: 0.3463 - acc: 0.8606 - val_loss: 0.3450 - val_acc: 0.8600
Epoch 4/50
9800/9800 [==============================] - 0s 43us/sample - loss: 0.3452 - acc: 0.8614 - val_loss: 0.3446 - val_acc: 0.8750
Epoch 5/50
9800/9800 [==============================] - 0s 39us/sample - loss: 0.3443 - acc: 0.8616 - val_loss: 0.3481 - val_acc: 0.8650
Epoch 6/50
9800/9800 [==============================] - 0s 40us/sample - loss: 0.3432 - acc: 0.8620 - val_loss: 0.3438 - val_acc: 0.8750
Epoch 7/50
9800/9800 [==============================] - 0s 42us/sample - loss: 0.3420 - acc: 0.8630 - val_loss: 0.3392 - val_acc: 0

Model classification accuracy on Validation data is 88.5% correct

In [88]:
y_pred1=model.predict(X_test)
y_pred1

array([[0.04133695],
       [0.04360014],
       [0.11772802],
       [0.16976884],
       [0.05642518],
       [0.03045702],
       [0.09824389],
       [0.0562281 ],
       [0.3058641 ],
       [0.7236124 ],
       [0.94592345],
       [0.91325176],
       [0.60569525],
       [0.50921553],
       [0.03244913],
       [0.09984845],
       [0.15928173],
       [0.17378032],
       [0.04993558],
       [0.04683152],
       [0.1125485 ],
       [0.02816239],
       [0.13606924],
       [0.13115531],
       [0.0813272 ],
       [0.45727634],
       [0.0644483 ],
       [0.03097999],
       [0.03582388],
       [0.07795912],
       [0.10743937],
       [0.06064105],
       [0.1678944 ],
       [0.03491145],
       [0.07004809],
       [0.6238847 ],
       [0.54216784],
       [0.0441024 ],
       [0.13250494],
       [0.041886  ],
       [0.08996207],
       [0.52599245],
       [0.03214043],
       [0.06608799],
       [0.13907951],
       [0.06203234],
       [0.04062799],
       [0.222

In [89]:
y_pred1=y_pred1>.5
y_pred1

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [

In [90]:
cm1=confusion_matrix(y_test, y_pred1)
cm1

array([[152,   8],
       [ 20,  20]], dtype=int64)